#!/bin/bash
echo 'Общее количество запросов по типу' > results/result_2.txt | cat access.log | awk '{print $6}' | sort | uniq -c | sort -nr | awk '{print $2, $1}' | sed 's/"//' >> results/result_2.txt

